# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Suhyune Son
title: Ph.D. Candidate, NLP & AI Lab., Korea University
#email: ssh5131@korea.ac.kr
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sonsuhyune
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: Suhyun Son
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I am a Ph.D student in [NLP&AI Lab](https://nlp.korea.ac.kr). at Korea University, advised by Prof. Heuiseok Lim.

  I am studying natural language processing with a particular focus on dialogue generation.

  <mark>Email</mark>: ssh5131@korea.ac.kr

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Korea University
        caption: 2021.09 - Present
        sub_title: Ph.D candidate in Computer Science
      - layout: top-middle
        title: Ewha Womans University
        caption: 2017.03 - 2021.08
        sub_title: B.S Degree Graduate in Department of Computer Science and Engineering
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#        description: | # this will include new lines to allow paragraphs
#          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#
#          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: International Conference # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Post-hoc Utterance Refining Method by Entity Mining for Faithful Knowledge Grounded Conversations"
        quote: >
          <mark>EMNLP 2023</mark>
          Yoonna Jang*, <b>Suhyune Son</b>*, Jeongwoo Lee*, Junyoung Son, Yuna Hur, Jungwoo Lim, Hyeonseok Moon, Kisu Yang, Heuiseok Lim

      - layout: top-middle
        title: "Call for Customized Conversation: Customized Conversation Grounding Persona and Knowledge"
        quote: |
          <mark>AAAI 2022</mark>
          Yoonna Jang, Jungwoo Lim, Yuna Hur, Dongsuk Oh, <b>Suhyune Son</b>, Yeonsoo Lee, Donghoon Shin, Seungryong Kim, Heuiseok Lim

  - title: International Journal # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        title: "An analysis on language transfer of pre-trained language model with cross-lingual post-training"
        quote: >2
          <mark>Expert Systems with Applications. 2025</mark>
          <b>Suhyune Son</b>, Chanjun Park, Jungseob Lee, Midan Shim, Chanhee Lee, Yoonna Jang, Jaehyung Seo, Jungwoo Lim, Heuiseok Lim

      - layout: top-middle
        title: "A large-scale dataset for korean document-level relation extraction from encyclopedia texts"
        quote: >2
          <mark>Applied Intelligence. 2024</mark>
          <b>Suhyune Son</b>, Jungwoo Lim, Seonmin Koo, Jinsung Kim, Younghoon Kim, Youngsik Lim, Dongseok Hyun, Heuiseok Lim

      - layout: top-middle
        title: "Analysis of the Effectiveness of Model, Data, and User-Centric Approaches for Chat Application: A Case Study of BlenderBot 2.0"
        quote: >2
          <mark>Applied Sciences. 2024</mark>
          Chanjun Park, Jungseob Lee, <b>Suhyune Son</b>, Kinam Park, Jungsun Jang, Heuiseok Lim


      - layout: top-middle
        title: "Intent classification and slot filling model for in-vehicle services in Korean"
        quote: >2
          <mark>Applied Sciences. 2022</mark>
          Jungwoo Lim*, <b>Suhyune Son*</b>, Songeun Lee, Changwoo Chun, Sungsoo Park, Yuna Hur, Heuiseok Lim

      - layout: top-middle
        title: "K-EPIC: Entity-perceived context representation in Korean relation extraction"
        quote: >
          <mark>Applied Sciences. 2021</mark>
          Yuna Hur*, <b>Suhyune Son</b>*, Midan Shim*, Jungwoo Lim*, Heuiseok Lim

      - layout: top-middle
        title: "A sequential and intensive weighted language modeling scheme for multi-task learning-based natural language understanding"
        quote: |
          <mark>Applied Sciences. 2021</mark>

          <b>Suhyune Son</b>, Seonjeong Hwang, Sohyeun Bae, Soo Jun Park, Jang-Hwan Choi


  - title: Domestic Conference # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        title: "Enhancing Empathetic Response Generation in Large Language Models based on Emotional Validation Theory"
        quote: >2
          <mark>The 36rd Annual Conference on Human & Cognitive Language Technology (HCLT 2024)</mark>
          <b>Suhyune Son</b>, Jungwoo Lim, Myunghoon Kang, Seongtae Hong, Yuna Hur, Aram So, Heuiseok Lim


      - layout: top-middle
        title: "Enhancing Open-Ended Knowledge Tracing with Prefix-Tuning"
        quote: >2
          <mark>The 35rd Annual Conference on Human & Cognitive Language Technology (HCLT 2023)</mark>
          <b>Suhyune Son</b>, Myunghoon Kang, Aram So, Heuiseok Lim

      - layout: top-middle
        title: "Data Augmentation for Generating Counter Narratives against Hate Speech"
        quote: >2
          <mark>The 34rd Annual Conference on Human & Cognitive Language Technology (HCLT 2022)</mark>
          Seungyoon Lee, <b>Suhyune Son</b>, Dahyun Jung, Chanjun Park, Aram So, Heuiseok Lim

      - layout: top-middle
        title: "Korean language model construction and comparative analysis with Cross-lingual Post-Training (XPT)"
        quote: >2
          <mark>The 34rd Annual Conference on Human & Cognitive Language Technology (HCLT 2022)</mark>
          <b>Suhyune Son</b>, Chanjun Park, Jungseob Lee, Midan Shim, Sunghyun Lee, JinWoo Lee, Aram So, Heuiseok Lim

      - layout: top-middle
        title: "Analysis on Question Understanding of Language Models using Clever Hans Tests"
        quote: >2
          <mark>The 33rd Annual Conference on Human & Cognitive Language Technology (HCLT 2021)</mark>
          Jungwoo Lim, Dongsuk Oh, Sungjin Park, Taesun Whang, Midan Shim, <b>Suhyune Son</b>, Yujin Kim, Heuiseok Lim

      - layout: top-middle
        title: "Directional Predictive Analysis of Pre-trained Language Models in Relation Extraction"
        quote: >2
          <mark>The 33rd Annual Conference on Human & Cognitive Language Technology (HCLT 2021)</mark>
          Yuna Hur, Dongsuk Oh, Myunghoon Kang, <b>Suhyune Son</b>, Aram So, Heuiseok Lim

      - layout: top-middle
        title: "A Comparative Study on Korean Relation Extraction with entity position information"
        quote: >2
          <mark>The 33rd Annual Conference on Human & Cognitive Language Technology (HCLT 2021)</mark>
          <b>Suhyune Son</b>, Yuna Hur, Jungwoo Lim, Midan Shim, Chanjun Park, Heuiseok Lim

  - title: Domestic Journal # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Korean and Multilingual Language Models Study for Cross-Lingual Post-Training (XPT)"
        quote: >2
          <mark>Journal of the Korea Convergence Society, 2022</mark>
          <b>Suhyune Son</b>, Chanjun Park, Jungseob Lee, Midan Shim, Chanhee Lee, Kinam Park, Heuiseok Lim

      - layout: top-middle
        title: "Empirical study on BlenderBot 2.0's errors analysis in terms of model, data and dialogue"
        quote: >2
          <mark>Journal of the Korea Convergence Society, 2021</mark>
          Jungseob Lee, <b>Suhyune Son</b>, Midan Shim, Yujin Kim, Chanjun Park, Aram So, Jeongbae Park, Heuiseok Lim
#
#      - layout: top-middle
#        title: "A Comparative Study on Korean Relation Extraction with entity position information"
#        quote: >2
#          <mark>The 33rd Annual Conference on Human & Cognitive Language Technology (HCLT 2021)</mark>
#          <b>Suhyune Son</b>, Yuna Hur, Jungwoo Lim, Midan Shim, Chanjun Park, Heuiseok Lim



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hyundai Motor Company
        caption: 2024 - 2025
        sub_title: Developed a model for TableQA based on noisy multi-table data provided by Hyundai Motor Company.
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
